In [11]:
import pandas as pd
import matplotlib.pyplot as plt

In [12]:
df = pd.read_csv("minhas-vendas.csv")
df.head()

         date product_category  units_sold  revenue customer_region
0  2026/03/01      Eletrônicos          12  1200.50           Norte
1  2026/03/02        Vestuário          45   890.20             Sul
2  2026/03/03      Eletrônicos           8   850.00           Leste
3  2026/03/04        Alimentos         120   600.75           Oeste
4  2026/03/05        Vestuário          30   600.00           Norte

In [13]:
df.dtypes

date                    str
product_category        str
units_sold            int64
revenue             float64
customer_region         str
dtype: object

In [17]:
df["date"] = pd.to_datetime(df["date"], format="%Y/%m/%d")

In [18]:
df.head()

        date product_category  units_sold  revenue customer_region
0 2026-03-01      Eletrônicos          12  1200.50           Norte
1 2026-03-02        Vestuário          45   890.20             Sul
2 2026-03-03      Eletrônicos           8   850.00           Leste
3 2026-03-04        Alimentos         120   600.75           Oeste
4 2026-03-05        Vestuário          30   600.00           Norte

In [20]:
df.dtypes

date                datetime64[us]
product_category               str
units_sold                   int64
revenue                    float64
customer_region                str
dtype: object